### ISSUE TITLE
有一点小问题，就是如果数据库表有变动 需要重新生成，重新生成 发现多了@Data的get set 等等方法，怎么过滤再次生成的时候也这么纯洁

### ISSUE THREAD

**Issue by xiangshiming1992** [softwareloop/mybatis-generator-lombok-plugin#6]
有一点小问题，就是如果数据库表有变动 需要重新生成，重新生成 发现多了@Data的get set 等等方法，怎么过滤再次生成的时候也这么纯洁

**Comment by softwareloop** [comment]
Sorry, this project's language for documentation and discussion is English.
