### ISSUE TITLE
two Mapper class would be in the result of XXXMapper class

### ISSUE THREAD

**Issue by 0kai** [softwareloop/mybatis-generator-lombok-plugin#7]
after I add LombokPlugin, it will add @Mapper to the XXXMapper class, so the class would be error;
![image](https://user-images.githubusercontent.com/1498653/37870626-4fbde0e0-300d-11e8-9e9f-fda52fc70fdd.png)

**Comment by softwareloop** [comment]
I can't find "tk.mybatis.mapper.common.Mapper" used anywhere in the plugin. Is it possible that your IDE added that import?

**Comment by 0kai** [comment]
yeah, I had add other plugin for it, so I fixed this in other way. Thanks~
