### ISSUE TITLE
mybatis 1.3.6 Useless

### ISSUE THREAD

**Issue by zhaozhiwei1992** [softwareloop/mybatis-generator-lombok-plugin#9]
<dependency>
        <groupId>com.softwareloop</groupId>
        <artifactId>mybatis-generator-lombok-plugin</artifactId>
        <version>1.1-SNAPSHOT</version>
 </dependency>
-- generalconfig.xml
    <plugin type="com.softwareloop.mybatis.generator.plugins.LombokPlugin"></plugin>

**Comment by softwareloop** [comment]
I guess you mean that there is a problem using the plugin with mybatis generator 1.3.6. You probably make a good comment. Can you articulate it?

**Comment by zhaozhiwei1992** [comment]
I put the LombokPlugin in my project and use a test case like this
```
  MyBatisGenerator myBatisGenerator = new MyBatisGenerator(config, shellCallback, warnings);
   myBatisGenerator.generate(null);
```
work,  thk you
